### ISSUE TITLE
Set supported python version to >=3.9 - 20

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-cluster-management-python-client#21]
[Auto generated]
Number: [#20]

**Comment by redhat-qe-bot2** [comment]
[38;5;135mopenshift-cluster-management-python-client[0m[pull_request][99bc-11ef-95c7-9f82fa1b364c][PR 20]: Closing issue for PR: Set supported python version to >=3.9.
PR was closed.
